/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.tesa;

import java.io.BufferedInputStream;
import java.io.InputStream;
import java.net.HttpURLConnection;
import java.net.URL;
import java.util.HashMap;
import java.util.Map;
import org.apache.commons.io.IOUtils;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.awt.Color;
import java.io.IOException;
import java.io.OutputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
/**
 *
 * @author pc0203
 */
public class MainFrame extends javax.swing.JFrame {
    public HashMap<String,String> data;
    public String code;
    public String token;
    public String urlPostData;
    public String urlDownload;
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        btnSendData = new javax.swing.JButton();
        btnSubmitText = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        textData = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        textCode = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        textToken = new javax.swing.JTextField();
        btnCreateCode = new javax.swing.JButton();
        textReport = new javax.swing.JLabel();
        btnGetData = new javax.swing.JButton();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnSendData.setText("Send data");
        btnSendData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSendDataMouseClicked(evt);
            }
        });
        btnSendData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendDataActionPerformed(evt);
            }
        });

        btnSubmitText.setText("Submit Text");

        textData.setColumns(20);
        textData.setRows(5);
        jScrollPane2.setViewportView(textData);

        jLabel1.setText("Code: ");

        jLabel3.setText("Token:");

        btnCreateCode.setText("Create code");
        btnCreateCode.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCreateCodeMouseClicked(evt);
            }
        });

        btnGetData.setText("Get data");
        btnGetData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGetDataMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(textCode, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(textToken)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(165, 165, 165)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnCreateCode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSendData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(btnSubmitText))
                    .addComponent(btnGetData, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(textReport, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCreateCode)
                        .addGap(10, 10, 10)
                        .addComponent(btnSendData)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnGetData)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(textCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(textToken, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSubmitText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textReport, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSendDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSendDataActionPerformed

    private void btnSendDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSendDataMouseClicked
        // TODO add your handling code here:
        String urlPost="http://tesa.me:8181/data?u=140896&o="+token+"&t=0";
        postData(urlPost, textData.getText());
        textReport.setForeground(Color.BLUE);
        textReport.setText("Send data successful!");
        if (textCode.getText().trim().length()==0||null==textCode.getText()) {
            textReport.setForeground(Color.RED);
            textReport.setText("Send data error!");
        }
       
    }//GEN-LAST:event_btnSendDataMouseClicked

    private void btnCreateCodeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCreateCodeMouseClicked
        // TODO add your handling code here:
        data=mapData();
        code=data.get("code");
        token=data.get("token");
        textCode.setText(code);
        textToken.setText(token);
        textData.setText("");
        textReport.setText("");
    }//GEN-LAST:event_btnCreateCodeMouseClicked

    private void btnGetDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGetDataMouseClicked
        // TODO add your handling code here:
        String token=textToken.getText();
        textData.setText(recevieData(token));
    }//GEN-LAST:event_btnGetDataMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        try {
            /* Set the Nimbus look and feel */
            //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
            /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
            * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
            */
            try {
                for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("Nimbus".equals(info.getName())) {
                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                        break;
                    }
                }
            } catch (ClassNotFoundException ex) {
                java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (InstantiationException ex) {
                java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
            //</editor-fold>
            
            /* Create and display the form */
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    
                    new MainFrame().setVisible(true);
                }
            });
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        //</editor-fold>
    }
      public static String recevieData(String token){
        String data="";
        try {
            HttpURLConnection connection = initHttpURLConnection("http://tesa.me:8181/data?u=1&o=" + token, "GET", "text/html;charset=utf-8");
            InputStream in = new BufferedInputStream(connection.getInputStream());
            data = IOUtils.toString(in, "UTF-8");
            Map<String,String> map = new ObjectMapper().readValue(data, HashMap.class);
            data=map.get("text");
        } catch (IOException e) {
            e.printStackTrace();
            System.exit(0);
        }
        return data;
     }
    public static HashMap<String,String> mapData(){
        HashMap<String,String> map=null;
        try {
            HttpURLConnection connection= initHttpURLConnection("http://tesa.me:8181/getcode?u=140896","GET","text/html;charset=utf-8");
            InputStream in = new BufferedInputStream(connection.getInputStream());
            String data  = IOUtils.toString(in, "UTF-8");
            System.out.println(data);
            map = new ObjectMapper().readValue(data, HashMap.class);

        } catch (Exception e) {
            e.printStackTrace();
        }
        return  map;
    }
  public void postData(String urlService, String data) {
        try {
            HttpURLConnection conn= initHttpURLConnection(urlService,"POST","\"application/json; charset=UTF-8\"");
            OutputStream os = conn.getOutputStream();
            os.write(data.getBytes("UTF-8"));
            os.close();
            InputStream in = new BufferedInputStream(conn.getInputStream());
            String result = IOUtils.toString(in, "UTF-8");
            in.close();
            conn.disconnect();
        } catch (IOException e) {
            e.printStackTrace();
            textReport.setForeground(Color.RED);
            textReport.setText("Send data error!");
        }
    }

     public static HttpURLConnection initHttpURLConnection(String urlService,String contentType,String requestMethod){
        URL url = null;
        HttpURLConnection conn=null;
        try {
            url = new URL(urlService);
            conn = (HttpURLConnection) url.openConnection();
            conn.setConnectTimeout(1000);
            conn.setRequestProperty("Content-Type", requestMethod);
            conn.setDoOutput(true);
            conn.setDoInput(true);
            conn.setRequestMethod(contentType);

        } catch (Exception e) {
            e.printStackTrace();
        }
        return conn;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateCode;
    private javax.swing.JButton btnGetData;
    private javax.swing.JButton btnSendData;
    private javax.swing.JButton btnSubmitText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField textCode;
    private javax.swing.JTextArea textData;
    private javax.swing.JLabel textReport;
    private javax.swing.JTextField textToken;
    // End of variables declaration//GEN-END:variables
}
